### ISSUE TITLE
Show local timezone instead of UTC?

### ISSUE THREAD

**Issue by alaendle** [co-log/co-log#217]
Should co-log always use UTC as time zone output?

Personally I'm unsure what is the "correct" behaviour, so I started this experiment to use the local time zone as an default instead.

Please note that this adds the time package as a dependency to co-log (but it was a transitive dependency before, so it shouldn't add to the footprint of the library).

So just tell me what do you think?

Corresponding pull request: https://github.com/kowainik/co-log/pull/216

**Comment by chshersh** [comment]
Hi @alaendle! Thanks for the idea 👍🏻 

I don't think we should change the time zone for "local time" by default. Usually, you have logs enabled on multiple deployed environments, and people from different countries and different time zones can use your system. So, using local time would be confusing in such a system, and UTC would be a better default.

I can see how using a local timezone can be convenient for the local development, but I think that it is better to allow creating of custom messages and formatting functions easier instead of changing the default and supporting another use case in the `co-log` as well. `co-log` is very flexible, and we can't realistically support all use-cases. But it focuses on extensibility, meaning that it should be easy to adjust `co-log` for your own use-case.

As a way forward further improvements, I can suggest you try to create a custom message with local timezone formatting in a separate project and see how much of the `co-log` you need to reimplement. After that we can see, if we can reexport more functions from `co-log` and refactor some of the internal machinery to make it easier to create custom messages.

**Comment by alaendle** [comment]
Hello @chshersh, 

you are right, it is at least arguable, if the local zone is a "better" default than UTC; but I wouldn't argue that forcing the the user to UTC is much better; in our environment the (centrally managed) servers have a configured time zone (according to there physical location) so all system logs show local time, while only `co-log` provides UTC - and that's the reason why I was looking for a way to include the time zone in the logging output (and the easiest way seemed to be the PR 😄 ). If I find time I will follow your advice and try to implement a solution "around" `co-log` (I will keep you posted if this happens).

May I express the hope that you take time zones into account if you refactor the time formatting (https://github.com/kowainik/co-log/issues/190)? Also if you forgot about the "hacked" `fmtRichMessageDefault` and `fmtSimpleRichMessageDefault` methods, you have to admit, that `showTime` and `builderDmyHMSz` look more natural if time zones are considered 😉 

And don't get me wrong, the whole thing was only intended as a starting point to discuss and maybe improve behaviour and not to force a breaking change by introducing another default.

**Comment by alaendle** [comment]
Hi @chshersh, 

I followed your suggestion and implemented as showcase demonstrating what is currently needed to include time zone support.

https://github.com/alaendle/co-log/commit/4a0ec59440b405586e32fefe3bc9920d89fba66e#diff-86ac990f34204f841ecda3acd3f4e381497096e7421680bf155a1bb1a9c7b14a

Since the field map is extensible all code duplication is related to formatting - as you've expected. I'm torn if this is a bad thing, one could argue that these are only implementation details and the only visible surface is the `LogAction` (so why care about the details behind it? it is "super encapsulated"); on the other hand we really need to duplicate almost all of the formatting code, so we couldn't participate if co-log improves and implements bugfixes or new features (e.g. adapts to new library or ghc versions 😉).

**Comment by alaendle** [comment]
RFC: A new approach to at least simplify the situation a little 😄 . What if we just allow `showTime` to consider offsets (o.k., a breaking change - but we could also consider to create a new `showTimeOffset`or something like that) and also expose `showThreadId`. With this small changes almost all duplicated code that needs to be implemented to show timezones is gone. See: 
https://github.com/alaendle/co-log/commit/cfe0f868c55e1ad3eb560b3f9bfacc9ac7affb80
If we agree on some form for sure I will create a new and clean PR.

**Comment by chshersh** [comment]
Hi @alaendle, sorry for the delays in my replies.

I'm currently in the process of splitting the old `co-log` repo into separate packages and I'm on the `co-log` itself at the moment. But it takes time to finish that work... I hope to finish it in the nearest week or so. 

I think your initial PR is a good implementation of how I see this to be implemented. But I'm concerned that the `FieldMap` contains all time actions by default. This is extra work on each logged message 😞 

I like your new idea a lot! To minimize the breakage, I vote for adding the `showTimeOffset` function separately (exporting `showThreadId` sounds good as well). Maybe, after that, we can add a separate tutorial to `co-log` about how to create your own message and formatter using the local time as an example. I'm not saying that you need to write this tutorial 🙂 But if you want to later, it would be a great documentation addition to the repo! 👏🏻

**Comment by alaendle** [comment]
@chshersh - no need to be sorry! This issue is old and I also rarely find time to worry about it. Nonetheless, let's improve things in the long-term. I created a PR that for now only contains the needed changes to `Message.hs` without any usage - to keep things as simple as possible at first.

**Comment by alaendle** [comment]
Haven't written a tutorial 😧 but with https://github.com/co-log/co-log/pull/226 everything is in place to easily show local timezones - so I close this issue (if documentation is needed a new issue referencing this issue could be created).
